
KSRC		= /lib/modules/$(shell uname -r)/build
V		= 0

# Build the ntrdma kernel module
LINUXCONFIG	+= CONFIG_NTRDMA=m
LINUXCONFIG	+= CONFIG_NTRDMA_DEBUG=y
LINUXCONFIG	+= CONFIG_NTRDMA_DEBUGFS=y
#LINUXCONFIG	+= CONFIG_NTRDMA_TRACE=y
LINUXCONFIG	+= CONFIG_NTRDMA_OS_LINUX=y
LINUXCONFIG	+= CONFIG_NTRDMA_IB_OFED=y
LINUXCONFIG	+= CONFIG_NTRDMA_MEM_LINUX=y
LINUXCONFIG	+= CONFIG_NTRDMA_VBELL_USE_SEQ=y
LINUXCONFIG	+= CONFIG_NTRDMA_ETH=y

# Configure for ntb and dma hardware
LINUXCONFIG	+= CONFIG_NTRDMA_NTB=y
LINUXCONFIG	+= CONFIG_NTRDMA_MAP_PHYS=y

# Configure for simulation over a tcp connection
#LINUXCONFIG	+= CONFIG_NTRDMA_TCP=y
#LINUXCONFIG	+= CONFIG_NTRDMA_MAP_VIRT=y

LINUXINCLUDE	= \
	-I$$(srctree)/arch/$$(SRCARCH)/include \
	-Iarch/$$(SRCARCH)/include/generated/uapi \
	-Iarch/$$(SRCARCH)/include/generated \
	$$(if $$(KBUILD_SRC), -I$$(srctree)/include) \
	-I$(PWD)/include -Iinclude \
	-I$$(srctree)/arch/$$(SRCARCH)/include/uapi \
	-Iarch/$$(SRCARCH)/include/generated/uapi \
	-I$$(srctree)/include/uapi \
	-Iinclude/generated/uapi \
	-include $$(srctree)/include/linux/kconfig.h \
	-include $(PWD)/config.h

MAKE_TARGETS	= all modules modules_install clean help
MAKE_OPTIONS	= -C $(KSRC) M=$(CURDIR) V=$(V) $(LINUXCONFIG)

modules: config.h
modules: MAKE_OPTIONS += LINUXINCLUDE='$(LINUXINCLUDE)'

install: modules_install

config.h: makefile
	@echo > config.h "/* Generated by Makefile */"
	@for E in ${LINUXCONFIG}; do echo >> config.h "#define $${E/=/ }" ; done

build_test: synopsis_ntrdma_ring test_ntrdma_ring

test: build_test
	./synopsis_ntrdma_ring
	./test_ntrdma_ring

$(MAKE_TARGETS):
	$(MAKE) $(MAKE_OPTIONS) $@

.PHONY: $(MAKE_TARGETS)

