obj-$(CONFIG_NTC) += ntc.o
obj-$(CONFIG_NTC) += ntc_phys.o
obj-$(CONFIG_NTC_TCP) += ntc_virt.o
obj-$(CONFIG_NTC_NTB) += ntc_ntb.o
obj-$(CONFIG_NTC_NTB_MSI) += ntc_ntb_msi.o
obj-$(CONFIG_NTC_TCP) += ntc_tcp.o
